SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 创建数据库
CREATE DATABASE IF NOT EXISTS `acedia-mysql-db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

-- GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'acedia-slave'@'%' IDENTIFIED BY 'acedia-slave@123';
-- FLUSH PRIVILEGES;


SET FOREIGN_KEY_CHECKS = 1;
