CREATE DATABASE IF NOT EXISTS `acedia-mysql-db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'acedia-slave'@'%' IDENTIFIED BY 'acedia-slave@123';

FLUSH PRIVILEGES;
