version: '3.8'

services:
  nginx-service:
    container_name: nginx-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=stable-alpine3.17-slim
    restart: always
    ports:
      - "8080:80"
    networks:
      my-network:
        ipv4_address: 172.23.0.55
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ../docker-volumes/nginx/html:/etc/nginx/html:rw
      - ../docker-volumes/nginx/logs:/var/log/nginx:rw
networks:
  my-network:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
