version: '3.8'

services:
  nacos-service:
    container_name: nacos-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NACOS_VERSION=v2.2.3-slim
    restart: on-failure
    ports:
      - "8848:8848"
      - "9847:9847"
      - "9848:9848"
      - "9849:9849"
    networks:
      my-network:
        ipv4_address: 172.23.0.4
    depends_on:
      - mysql-db
    env_file:
      - ./conf/env/nacos-standlone-mysql.env
    environment:
      - NACOS_APPLICATION_PORT=8848
      - JVM_XMS=512m
      - JVM_MMS=320m
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_devtest
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos@tuoyingtao.com
      - management.endpoints.web.exposure.include=*
    volumes:
      - ./conf/application.properties:/home/nacos/conf/application.properties:rw
      - ./conf/plugins:/home/nacos/plugins:rw
      - ../docker-volumes/nacos/logs:/home/nacos/logs:rw
      - ../docker-volumes/nacos/standalone-logs/:/home/nacos/logs:rw
networks:
  my-network:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
