version: '3.8'

services:
  acedia-nacos-service:
    container_name: acedia-nacos-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NACOS_VERSION=v2.4.3
    restart: on-failure
    ports:
      - "8848:8848"
      - "9847:9847"
      - "9848:9848"
      - "9849:9849"
    networks:
      acedia-network:
        ipv4_address: 172.23.10.4
#    depends_on:
#      - acedia-mysql-db
    env_file:
      - env/nacos-standlone-mysql.env
    environment:
      - JVM_XMS=512m
      - JVM_MMS=320m
      - management.endpoints.web.exposure.include=*
    volumes:
      - ./conf/application.properties:/home/nacos/conf/application.properties:rw
      - ./plugins:/home/nacos/plugins:rw
      - ../docker-volumes/nacos/logs:/home/nacos/logs:rw
      - ../docker-volumes/nacos/standalone-logs/:/home/nacos/logs:rw
networks:
  acedia-network:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.23.10.0/24
          gateway: 172.23.10.1
