version: '3.8'

services:
  nexus3-service:
    container_name: nexus3-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REDIS_VERSION=3.62.0
    restart: always
    ports:
      - "8081:8081" # 后台端口
      - "6000:6000" # 代理端口
      - "6001:6001" # 私服端口
    networks:
      my-network:
        ipv4_address: 172.23.0.6
    environment:
      - "INSTALL4J_ADD_VM_PARAMS=-Xms128m -Xmx512m -XX:MaxDirectMemorySize=512m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
      - TZ="Asia/Shanghai"
    volumes:
      - ./conf/nexus.properties:/opt/sonatype/nexus/etc/nexus.properties:rw
      - ../docker-volumes/nexus3/logs:/nexus-log:rw
      - ../docker-volumes/nexus3/data:/nexus-data:rw
#    command: ["sh", "-c", "cat", "/nexus-data/admin.password && echo"]
#    command: ["sh", "-c", "cat /nexus-data/admin.password && sleep infinity"]
networks:
  my-network:
    driver: bridge
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
