# 构建时指定的参数变量
ARG NEXUS3_VERSION="latest"

# 基础镜像
FROM sonatype/nexus3:${NEXUS3_VERSION}

# 镜像维护者
MAINTAINER TuoYingtao

LABEL maintainer="TuoYingtao" description="Nexus3 服务" version="${NEXUS3_VERSION}"
