version: '3.8'

services:
  mysql-db:
    container_name: mysql-db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=8.2.0
    restart: always
    ports:
      - "3306:3306"
    networks:
      my-network:
        ipv4_address: 172.23.0.2
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./conf.d:/etc/mysql/conf.d:ro
      - ../docker-volumes/mysql/logs:/logs:rw
      - ../docker-volumes/mysql/data:/var/lib/mysql:rw
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    command: [
      'mysqld',
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--innodb-buffer-pool-size=80M',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
    ]
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1", "-uroot", "-123456" ]
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 5
networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
